// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGPH0Q0L2rUgTKGoAkHXkMIOhZ7VVdibs',
    appId: '1:746032600431:web:2e9fea79a1c68169bb049a',
    messagingSenderId: '746032600431',
    projectId: 'coffee-cat-8b348',
    authDomain: 'coffee-cat-8b348.firebaseapp.com',
    storageBucket: 'coffee-cat-8b348.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYpUFtAd0e3E4C3fAx2ldmthgJ3dFrelM',
    appId: '1:746032600431:android:e61f4226be008a82bb049a',
    messagingSenderId: '746032600431',
    projectId: 'coffee-cat-8b348',
    storageBucket: 'coffee-cat-8b348.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFKXEFwUSeeR9VZe6HyQCPiNm0C7xnAB4',
    appId: '1:746032600431:ios:fb17e63f096390dbbb049a',
    messagingSenderId: '746032600431',
    projectId: 'coffee-cat-8b348',
    storageBucket: 'coffee-cat-8b348.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFKXEFwUSeeR9VZe6HyQCPiNm0C7xnAB4',
    appId: '1:746032600431:ios:fb17e63f096390dbbb049a',
    messagingSenderId: '746032600431',
    projectId: 'coffee-cat-8b348',
    storageBucket: 'coffee-cat-8b348.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGPH0Q0L2rUgTKGoAkHXkMIOhZ7VVdibs',
    appId: '1:746032600431:web:204314d1bf781a61bb049a',
    messagingSenderId: '746032600431',
    projectId: 'coffee-cat-8b348',
    authDomain: 'coffee-cat-8b348.firebaseapp.com',
    storageBucket: 'coffee-cat-8b348.firebasestorage.app',
  );
}
